version: "3.8"

services:
  # Service for FastAPI
  fastapi:
    build: .
    container_name: fastapi_service_augustine
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis  # Wait for Redis to be up

  # Service for Celery worker
  celery:
    build: .
    container_name: celery_service_augustine
    command: ["celery", "-A", "celery_tasks.celery", "worker", "--loglevel=info","--pool=solo"]
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis    # Wait for Redis to be up

  # Redis service
  redis:
    image: "redis:alpine"
    container_name: redis_service_augustine
    ports:
      - "6379:6379"
